"use client";

import {
  ArrowLeft, Bot, Camera, CheckCircle2, CircleDollarSign, Clock3, Copy,
  ExternalLink, Gauge, Globe2, Lightbulb, MapPin, MessageSquareText, Phone,
  Search, ShieldCheck, Sparkles, Star, Target, TriangleAlert,
} from "lucide-react";
import { useRouter } from "next/navigation";
import type { MissionCompany } from "@/lib/engines/mission-engine";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

interface Props { company: MissionCompany }
type Area = { id:string; label:string; icon:typeof Globe2; score:number; status:string; summary:string; problems:string[]; opportunities:string[]; accent:string; bg:string };

const money = (value:number) => new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL", maximumFractionDigits:0 }).format(value);
const priority = (value:MissionCompany["leadScore"]["priority"]) => value === "high" ? "Alta" : value === "medium" ? "Média" : "Baixa";
const chance = (company:MissionCompany) => Math.min(96, Math.max(35, Math.round((company.leadScore.score + company.leadScore.confidence) / 2)));

function radial(score:number) {
  return { background: `conic-gradient(rgb(139 92 246) ${score * 3.6}deg, rgb(39 39 42) 0deg)` };
}

function areas(company:MissionCompany):Area[] {
  const reputation = Math.min(100, Math.round(company.rating * 16 + Math.min(company.reviews,300) / 8));
  return [
    { id:"website", label:"Website", icon:Globe2, score:company.websiteAnalysis.score, status:company.websiteAnalysis.scoreLabel, summary:company.websiteAnalysis.commercialDiagnosis, problems:company.websiteAnalysis.commercialProblems, opportunities:company.websiteAnalysis.recommendedServices, accent:"text-sky-600", bg:"bg-sky-500/5 border-sky-500/20" },
    { id:"seo", label:"SEO local", icon:Search, score:company.seoAnalysis.score, status:company.seoAnalysis.scoreLabel, summary:`Posição local estimada: ${company.seoAnalysis.estimatedLocalPosition}ª. ${company.seoAnalysis.hasLocalPresence ? "Há presença local, mas ela ainda pode ser ampliada." : "A empresa ainda não domina as buscas locais."}`, problems:company.seoAnalysis.problems, opportunities:company.seoAnalysis.opportunities, accent:"text-indigo-600", bg:"bg-indigo-500/5 border-indigo-500/20" },
    { id:"instagram", label:"Instagram", icon:Camera, score:company.instagramAnalysis.score, status:company.instagramAnalysis.scoreLabel, summary:company.instagramAnalysis.commercialDiagnosis, problems:company.instagramAnalysis.commercialProblems, opportunities:company.instagramAnalysis.recommendedServices, accent:"text-fuchsia-600", bg:"bg-fuchsia-500/5 border-fuchsia-500/20" },
    { id:"google", label:"Google", icon:Star, score:reputation, status:reputation >= 75 ? "Forte" : reputation >= 50 ? "Regular" : "Fraca", summary:`${company.rating.toFixed(1)} estrelas em ${company.reviews} avaliações públicas.`, problems:company.reviews < 50 ? ["Poucas avaliações para dominar a busca local"] : ["A reputação positiva ainda não está sendo usada em toda a jornada de venda"], opportunities:["Prova social no site", "Campanha contínua de avaliações", "Respostas estratégicas no Google"], accent:"text-emerald-600", bg:"bg-emerald-500/5 border-emerald-500/20" },
  ];
}

function ScoreRing({ value, label }:{ value:number; label:string }) {
  return <div className="flex items-center gap-4"><div className="grid h-24 w-24 place-items-center rounded-full p-2" style={radial(value)}><div className="grid h-full w-full place-items-center rounded-full bg-zinc-950"><div className="text-center"><p className="text-2xl font-semibold text-white">{value}</p><p className="text-[10px] uppercase tracking-[.16em] text-zinc-500">/100</p></div></div></div><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">{label}</p><p className="mt-1 text-sm text-zinc-300">Lead qualificado</p></div></div>
}

function AreaCard({ area }:{ area:Area }) {
  const Icon = area.icon;
  return <section id={area.id} className="scroll-mt-28"><Card className={`rounded-3xl border p-6 shadow-none sm:p-7 ${area.bg}`}><div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-3"><div className="rounded-2xl border bg-background p-3"><Icon className={`h-5 w-5 ${area.accent}`} /></div><div><h2 className="text-xl font-semibold">{area.label}</h2><p className="text-sm text-muted-foreground">{area.status}</p></div></div><p className="mt-5 leading-7 text-muted-foreground">{area.summary}</p></div><div className="min-w-40 rounded-2xl border bg-background/80 p-4"><p className="text-xs uppercase tracking-[.14em] text-muted-foreground">Score</p><p className="mt-1 text-4xl font-semibold">{area.score}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-foreground" style={{width:`${area.score}%`}} /></div></div></div><div className="mt-7 grid gap-5 md:grid-cols-2"><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Riscos detectados</p><div className="space-y-3">{area.problems.slice(0,3).map(item=><div key={item} className="flex gap-3 text-sm leading-6"><TriangleAlert className="mt-1 h-4 w-4 shrink-0 text-amber-500" /><span>{item}</span></div>)}</div></div><div><p className="mb-3 text-xs font-semibold uppercase tracking-[.14em] text-muted-foreground">Ações recomendadas</p><div className="space-y-3">{area.opportunities.slice(0,3).map(item=><div key={item} className="flex gap-3 text-sm leading-6"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-emerald-500" /><span>{item}</span></div>)}</div></div></div></Card></section>
}

export function CompanyIntelligenceReport({ company }:Props) {
  const router = useRouter();
  const reportAreas = areas(company);
  const topServices = Array.from(new Set([...company.websiteAnalysis.recommendedServices, ...company.instagramAnalysis.recommendedServices, ...company.seoAnalysis.opportunities])).slice(0,4);
  const closeChance = chance(company);
  const urgency = company.leadScore.score >= 80 ? "Urgente" : company.leadScore.score >= 65 ? "Alta" : "Moderada";
  const copy = async (text:string) => { try { await navigator.clipboard.writeText(text); } catch { window.alert(text); } };

  return <div className="min-h-screen bg-background pb-24">
    <div className="sticky top-0 z-30 border-b bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center gap-3 overflow-x-auto px-4 py-3 sm:px-6 lg:px-8"><Button variant="ghost" size="sm" onClick={()=>router.push("/mission")}><ArrowLeft className="mr-2 h-4 w-4" />Missão</Button><div className="h-5 w-px shrink-0 bg-border" />{[["summary","Resumo"],["diagnosis","Diagnóstico"],["opportunities","Oportunidades"],["plan","Plano"],["outreach","Abordagem"]].map(([id,label])=><a key={id} href={`#${id}`} className="shrink-0 rounded-xl px-3 py-2 text-sm text-muted-foreground transition hover:bg-muted hover:text-foreground">{label}</a>)}</div></div>

    <main className="mx-auto max-w-7xl space-y-12 px-4 pt-8 sm:px-6 lg:px-8">
      <section className="overflow-hidden rounded-[32px] border border-zinc-800 bg-zinc-950 text-white shadow-2xl shadow-violet-500/5"><div className="relative p-7 sm:p-10"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_top_right,rgba(139,92,246,.35),transparent_35%)]" /><div className="relative grid gap-10 xl:grid-cols-[1fr_auto]"><div><Badge className="border-violet-400/20 bg-violet-400/10 text-violet-200"><Sparkles className="mr-1.5 h-3.5 w-3.5" />Commercial Intelligence Cockpit</Badge><h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">{company.name}</h1><div className="mt-4 flex flex-wrap gap-4 text-sm text-zinc-400"><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4" />{company.city}</span><span className="inline-flex items-center gap-2"><Star className="h-4 w-4 fill-amber-400 text-amber-400" />{company.rating.toFixed(1)} ({company.reviews})</span><span className="inline-flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-400" />Confiança {company.leadScore.confidence}%</span></div><div className="mt-7 flex flex-wrap gap-2"><Badge className="bg-red-500/15 text-red-200 hover:bg-red-500/15">Urgência {urgency}</Badge><Badge className="bg-emerald-500/15 text-emerald-200 hover:bg-emerald-500/15">Potencial {money(company.websiteAnalysis.estimatedSaleMax)}</Badge><Badge className="bg-white/10 text-zinc-200 hover:bg-white/10">Prioridade {priority(company.leadScore.priority)}</Badge></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><ScoreRing value={company.leadScore.score} label="Opportunity score" /><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10"><div className="bg-zinc-950 p-4"><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Chance</p><p className="mt-2 text-2xl font-semibold">{closeChance}%</p></div><div className="bg-zinc-950 p-4"><p className="text-[10px] uppercase tracking-[.14em] text-zinc-500">Ticket</p><p className="mt-2 text-2xl font-semibold">{money(company.websiteAnalysis.estimatedSaleMax)}</p></div></div></div></div></div></section>

      <section id="summary" className="scroll-mt-28 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><Card className="rounded-3xl border-violet-500/20 bg-violet-500/5 p-7 shadow-none"><div className="flex gap-4"><Bot className="mt-1 h-6 w-6 shrink-0 text-violet-500" /><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">IA detectou</p><h2 className="mt-2 text-2xl font-semibold">O melhor caminho para fechar esta conta</h2><p className="mt-4 text-base leading-8 text-muted-foreground">{company.name} combina reputação de {company.rating.toFixed(1)} estrelas com uma lacuna comercial clara: {company.leadScore.reasons[0]?.toLowerCase() ?? "presença digital abaixo do potencial"}. A entrada recomendada é {topServices[0]?.toLowerCase() ?? "uma solução digital orientada à conversão"}, com ticket entre {money(company.websiteAnalysis.estimatedSaleMin)} e {money(company.websiteAnalysis.estimatedSaleMax)}.</p></div></div></Card><Card className="rounded-3xl p-7 shadow-none"><div className="flex items-center gap-3"><Gauge className="h-5 w-5 text-violet-500" /><h3 className="font-semibold">Leitura em 5 segundos</h3></div><div className="mt-5 space-y-3">{[(company.websiteAnalysis.hasWebsite?"Website encontrado":"Sem website: oportunidade imediata"),(company.instagramAnalysis.profileFound?"Instagram ativo para abordagem":"Presença social ausente"),(company.rating >= 4.5?"Google forte e com prova social":"Reputação precisa de fortalecimento"),`${company.leadScore.confidence}% de confiança na qualificação`].map(item=><div key={item} className="flex gap-3 text-sm"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-500" /><span>{item}</span></div>)}</div></Card></section>

      <section id="diagnosis" className="scroll-mt-28"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">Cockpit de diagnóstico</p><h2 className="mt-2 text-3xl font-semibold">Onde está o dinheiro</h2></div><div className="grid gap-5 xl:grid-cols-2">{reportAreas.map(area=><AreaCard key={area.id} area={area} />)}</div></section>

      <section id="opportunities" className="scroll-mt-28"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><CircleDollarSign className="h-7 w-7 text-emerald-600" /><h2 className="mt-4 text-3xl font-semibold">Oportunidades priorizadas</h2><p className="mt-3 leading-7 text-muted-foreground">Serviços ordenados por impacto, facilidade de abertura e potencial de receita.</p></div><div className="grid gap-4 sm:grid-cols-2">{topServices.map((service,index)=><Card key={service} className="rounded-3xl p-6 shadow-none"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-foreground font-semibold text-background">{index+1}</div><Badge variant="outline">{index===0?"Prioridade máxima":"Complementar"}</Badge></div><h3 className="mt-5 text-lg font-semibold">{service}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{index===0?"Melhor ponto de entrada para gerar valor e abrir a negociação.":"Aumenta ticket, retenção e percepção de solução completa."}</p></Card>)}</div></div></section>

      <section id="plan" className="scroll-mt-28"><Card className="rounded-3xl p-7 shadow-none"><div className="flex items-center gap-3"><Clock3 className="h-5 w-5 text-violet-500" /><h2 className="text-xl font-semibold">Cadência de fechamento</h2></div><div className="mt-7 grid gap-4 md:grid-cols-4">{[["Hoje","Contato inicial","Abra com a dor principal."],["D+2","Prova de valor","Envie um insight objetivo."],["D+5","Reunião","Apresente escopo e ticket."],["D+8","Fechamento","Trate objeções e avance."]].map(([day,title,text],index)=><div key={day} className="relative rounded-2xl border bg-muted/20 p-5"><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">{day}</p><p className="mt-3 font-semibold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p>{index<3?<div className="absolute -right-2 top-1/2 hidden h-px w-4 bg-border md:block" />:null}</div>)}</div></Card></section>

      <section id="outreach" className="scroll-mt-28"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">Kit comercial</p><h2 className="mt-2 text-3xl font-semibold">Abordagens prontas</h2></div><div className="grid gap-5 lg:grid-cols-3">{[{title:"WhatsApp",icon:MessageSquareText,text:company.outreach.message,accent:"text-emerald-600"},{title:"E-mail",icon:ExternalLink,text:`Assunto: ${company.outreach.subject}\n\n${company.outreach.message}`,accent:"text-sky-600"},{title:"Ligação",icon:Phone,text:company.outreach.callOpening,accent:"text-violet-600"}].map(item=>{const Icon=item.icon;return <Card key={item.title} className="rounded-3xl p-6 shadow-none"><Icon className={`h-5 w-5 ${item.accent}`} /><h3 className="mt-4 font-semibold">{item.title}</h3><p className="mt-3 line-clamp-6 whitespace-pre-line text-sm leading-6 text-muted-foreground">{item.text}</p><Button variant="outline" className="mt-5 w-full" onClick={()=>copy(item.text)}><Copy className="mr-2 h-4 w-4" />Copiar</Button></Card>})}</div></section>

      <Card className="rounded-3xl border-zinc-800 bg-zinc-950 p-7 text-white shadow-none"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><Lightbulb className="mt-1 h-6 w-6 text-amber-300" /><div><p className="text-xs uppercase tracking-[.16em] text-zinc-500">Próxima melhor ação</p><h2 className="mt-2 text-xl font-semibold">Comece oferecendo {topServices[0]?.toLowerCase() ?? "uma solução orientada à conversão"}.</h2></div></div><Button onClick={()=>document.querySelector("#outreach")?.scrollIntoView({behavior:"smooth"})}><Target className="mr-2 h-4 w-4" />Abrir abordagem</Button></div></Card>
    </main>
  </div>
}
